package engine_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/vatsalpatel/sqlette/internal/assert"
	"github.com/vatsalpatel/sqlette/internal/engine"
	"github.com/vatsalpatel/sqlette/internal/pager"
	"github.com/vatsalpatel/sqlette/internal/values"
)

// testdata/pre-m6.db was written by the engine as it stood at 777a9f4 — before
// the btree keys became []byte compared through an injected comparator. Table
// cells were supposed to keep their exact layout across that refactor; this is
// the test that says so, rather than the commit message.
//
// It was generated by running, against that build:
//
//	CREATE TABLE nums (n INT, label TEXT)
//	CREATE TABLE mixed (i INT, r REAL, t TEXT)
//	INSERT 1000 rows into nums, plus three into mixed
//	DELETE FROM nums WHERE n % 7 = 0
//	UPDATE nums SET label = '<fixtureNewLabel>' WHERE n % 11 = 0
//
// The shape is deliberate: 1000 rows overflow a single leaf several times over,
// so the file has a root interior node and the scan has to route through it; the
// scattered delete leaves repacked leaves behind; the update grew payloads, so
// cells moved. Those are the structures whose decoding the refactor touched.
const (
	fixtureRows      = 1000
	fixtureDeleteMod = 7
	fixtureUpdateMod = 11
	fixtureNewLabel  = "updated-to-a-rather-longer-label"
)

// wantNums derives the expected contents from the rules above rather than from
// whatever the code happens to return today.
func wantNums() [][]values.Value {
	var want [][]values.Value
	for n := 1; n <= fixtureRows; n++ {
		if n%fixtureDeleteMod == 0 {
			continue
		}
		label := fmt.Sprintf("row-%04d", n)
		if n%fixtureUpdateMod == 0 {
			label = fixtureNewLabel
		}
		want = append(want, []values.Value{values.NewInteger(int64(n)), values.NewText(label)})
	}
	return want
}

// copyFixture hands back a scratch copy. Opening a fixture in place would let
// the first run mutate the committed file and every run after that would be
// asserting against whatever the previous one wrote.
func copyFixture(t *testing.T, name string) string {
	t.Helper()
	src, err := os.ReadFile(filepath.Join("testdata", name))
	assert.NoError(t, err)
	dst := filepath.Join(t.TempDir(), "test.db")
	assert.NoError(t, os.WriteFile(dst, src, 0o644))
	return dst
}

func TestPreM6FileOpensScansAndMutates(t *testing.T) {
	path := copyFixture(t, "pre-m6.db")

	// Guard the fixture itself: a regenerated one-page file would still pass
	// every assertion below while proving nothing about interior nodes.
	info, err := os.Stat(path)
	assert.NoError(t, err)
	if pages := info.Size() / pager.PageSize; pages < 8 {
		t.Fatalf("fixture is only %d pages — too small to have split, so it cannot exercise interior cells", pages)
	}

	eng, err := engine.Open(path)
	assert.NoError(t, err)

	res := mustExec(t, eng, "SELECT * FROM nums")
	assert.DeepEqual(t, wantNums(), res.Rows)

	res = mustExec(t, eng, "SELECT * FROM mixed")
	assert.DeepEqual(t, [][]values.Value{
		{values.NewInteger(1), values.NewReal(1.5), values.NewText("one")},
		{values.NewInteger(2), values.NewReal(2.5), values.NewNull()},
		{values.NewNull(), values.NewNull(), values.NewText("three")},
	}, res.Rows)

	// Writing new pages into an old file is the other half of compatibility:
	// reading it back is not much use if a write corrupts it.
	mustExec(t, eng, "INSERT INTO nums VALUES (1001, 'written-after-the-refactor')")
	mustExec(t, eng, "UPDATE nums SET label = 'changed' WHERE n = 1")
	mustExec(t, eng, "DELETE FROM nums WHERE n = 2")
	assert.NoError(t, eng.Close())

	eng, err = engine.Open(path)
	assert.NoError(t, err)
	defer eng.Close()

	res = mustExec(t, eng, "SELECT label FROM nums WHERE n = 1")
	assert.DeepEqual(t, [][]values.Value{{values.NewText("changed")}}, res.Rows)

	res = mustExec(t, eng, "SELECT * FROM nums WHERE n = 2")
	assert.Equal(t, 0, len(res.Rows))

	res = mustExec(t, eng, "SELECT label FROM nums WHERE n = 1001")
	assert.DeepEqual(t, [][]values.Value{{values.NewText("written-after-the-refactor")}}, res.Rows)

	// One row deleted, one added.
	res = mustExec(t, eng, "SELECT * FROM nums")
	assert.Equal(t, len(wantNums()), len(res.Rows))
}
